;; WebAssembly text format code generated by the hydra compiler.

(module
  (import "hydra" "printi" (func $printi (param i32) (result i32)))
  (func (export "main") 
		(result i32)
    (local $x i32)
    i32.const 1
    local.set $x
		local.get $x
    i32.const 1
    i32.eq
		if
    i32.const 1
		call $printi
		drop
		else
		i32.const 0
    i32.const 1
		i32.sub
		call $printi
		drop
		end
		i32.const 0
	)
)
