;; WebAssembly text format code generated by the hydra compiler.

(module
  (import "hydra" "add" (func $add (param i32) (param i32) (result i32)))
  (import "hydra" "get" (func $get (param i32) (param i32) (result i32)))
  (import "hydra" "new" (func $new (param i32) (result i32)))
  (import "hydra" "printc" (func $printc (param i32) (result i32)))
  (import "hydra" "printi" (func $printi (param i32) (result i32)))
  (import "hydra" "println" (func $println (result i32)))
  (import "hydra" "prints" (func $prints (param i32) (result i32)))
  (import "hydra" "readi" (func $readi (result i32)))
  (import "hydra" "reads" (func $reads (result i32)))
  (import "hydra" "set" (func $set (param i32) (param i32) (param i32) (result i32)))
  (import "hydra" "size" (func $size (param i32) (result i32)))
  (func (export "main") 
		(result i32)
    (local $x i32)
    (local $y i32)
    i32.const 20
    local.set $y
		i32.const 0
	)
)
