namespace Hydra_compiler
{   
    public enum TokenCategory
    {
        //Keywords
        BREAK, ELIF, ELSE, FALSE, IF, RETURN, TRUE, VAR, WHILE, MAIN, PRINTI, PRINTC, PRINTS, PRINTLN, READI, READS,
        NEW, SIZE, ADD, GET, SET,
        //IDENTIFIER
        IDENTIFIER,
        //Extras
        EOL,EOF, BAD_TOKEN,
        //LITERALS
        INT_LITERAL, CHAR_LITERAL, STRING_LITERAL,
        //Operators
        PLUS, TIMES, OPEN_PAR, CLOSE_PAR, NEG, DIV, MOD, NOT, AND, OR, EQUALTO, NOTEQUALTO, GREATER,
        LESS, GREATEREQUAL, LESSEQUAL, PLUSPLUS, LESSLESS, PLUSEQUAL, SUBTRACEQUAL, OPEN_CURLY, CLOSE_CURLY,
        OPEN_BRAC, CLOSE_BRAC, ASSIGN, COMMA
    }
}   